# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

#trigger defines when a pipeline will run
#list-of-branches syntax:
# trigger:
# - main
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - SimpleOrderApp

#short for agent pool as in "build agent"

pool:
  vmImage: 'ubuntu-latest'

#variables common to multiple steps
variables:
  buildConfiguration: 'Release'

#these steps are run in sequence by the build agant,
#in a directory that contains the most recent push on that branch of the repo
steps:

- task: UseDotNet@2
  displayName: ".NET Core 3.1.x"
  inputs:
    version: '3.1.x'
    packageType: sdk


- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: SimpleOrderApp

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'f3f9f21d-d2c7-4e29-8aa7-6beab2a7e2e8'
    appName: SimpleOrderAppWebApp20201202134103
    package: $(System.DefaultWorkingDirectory)/**/*.zip